=== rogmed/DAM/M04A_Lenguaes_de_marcas/Actividad02/Validado XSD/vehiculos.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="vehiculos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vehiculo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9]*"/>
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="modelo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9]*"/>
                                        <xs:maxLength value="20"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="matricula">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9][0-9][0-9][0-9][-][A-Z][A-Z][A-Z]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="puertas">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:enumeration value="0"/>
                                        <xs:enumeration value="2"/>
                                        <xs:enumeration value="3"/>
                                        <xs:enumeration value="5"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="foto">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="http[s]*://[^~,]*"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="color" type="xs:string"/>
                            <xs:element name="tipo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Coche"/>
                                        <xs:enumeration value="Moto"/>
                                        <xs:enumeration value="CamiÃ³n"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="precio" type="xs:double"/>
                            <xs:element name="comentario">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rogmed/DAM/M04A_Lenguaes_de_marcas/Actividad02/Validado XSD/vehiculos.xml
<?xml version="1.0" encoding="UTF-8"?>
<vehiculos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="vehiculos.xsd">
    <vehiculo>
        <marca>Toyota</marca>
        <modelo>Auris</modelo>
        <matricula>3511-BGH</matricula>
        <puertas>5</puertas>
        <foto>https://imgsvrcars-a.akamaihd.net/images/2018/3/Toyota-Auris/x.jpg/Toyota-Auris-1.jpg</foto>
        <color>rojo</color>
        <tipo>Coche</tipo>
        <precio>12000</precio>
        <comentario>El Toyota Auris es un automóvil de turismo.</comentario>
    </vehiculo>
    <vehiculo>
        <marca>Yamaha</marca>
        <modelo>R1</modelo>
        <matricula>7854-NKD</matricula>
        <puertas>0</puertas>
        <foto>https://i.ytimg.com/vi/ZuRVzLmd8Og/maxresdefault.jpg</foto>
        <color>azul</color>
        <tipo>Moto</tipo>
        <precio>15000</precio>
        <comentario>La Yamaha R1 es una moto deportiva.</comentario>
    </vehiculo>
    <vehiculo>
        <marca>Mercedes</marca>
        <modelo>Actros</modelo>
        <matricula>8261-QJM</matricula>
        <puertas>2</puertas>
        <foto>https://cdn.motor1.com/images/mgl/8J78P/s1/2018-mercedes-benz-actros.jpg</foto>
        <color>rojo</color>
        <tipo>Camión</tipo>
        <precio>60000</precio>
        <comentario>Camion para transporte de mercancias.</comentario>
    </vehiculo>
</vehiculos>
